[package]
name = 'orbweaver_r'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'orbweaver'

[dependencies]
extendr-api = { version = "0.6", features = ["serde"] }
orbweaver = { version = "0.9.0" }
