[package]
name = 'orbweaver_r'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'orbweaver'

[dependencies]
# extendr-api = { version = "0.6", features = ["serde"] }
extendr-api = { git = "https://github.com/extendr/extendr.git", rev = "544b38b141640199aaee86e589abaf8ec73c6601" }
orbweaver = { version = "0.10.1" }
